### PR TITLE
fix: read encrypted xlsx file exception

### LINKED ISSUE #393: [Bug] read encrypted xlsx file exception
### Search before asking

- [x] I searched in the [issues](https://github.com/fast-excel/fastexcel/issues) and found nothing similar.

### Fastexcel version

1.2.0

### JDK version

1.8

### Operating system

_No response_

#### Test Case

[delei-easyexcel-issue-3463](https://github.com/delei/fastexcel-issue/blob/main/src/test/java/cn/deleiguo/issue/easyexcel/issue3463/Issue3463Test.java)

```java
public class IssueTest {

    @Test
    void fileTest() throws Exception {
        String password = "123456";
        File testFile = TestFileUtil.createNewFile(TestFileUtil.getPath() + "/easyexcel/issue-3463.xlsx");
        FastExcel.write(Files.newOutputStream(testFile.toPath()), DemoData.class)
                .excelType(ExcelTypeEnum.XLSX)
                .password(password)
                .sheet()
                .doWrite(demoData(10));
        FastExcel.read(testFile, DemoData.class, new CustomReadListener())
                .excelType(ExcelTypeEnum.XLSX)
                .password(password)
                .sheet()
                .doReadSync();
    }

    @Test
    void fileStreamTest() throws Exception {
        String password = "123456";
        File testFile = TestFileUtil.createNewFile(TestFileUtil.getPath() + "/easyexcel/issue-3463.xlsx");
        FastExcel.write(Files.newOutputStream(testFile.toPath()), DemoData.class)
                .excelType(ExcelTypeEnum.XLSX)
                .password(password)
                .sheet()
                .doWrite(demoData(10));
        FastExcel.read(Files.newInputStream(testFile.toPath()), DemoData.class, new CustomReadListener())
                .excelType(ExcelTypeEnum.XLSX)
                .password(password)
                .sheet()
                .doReadSync();
    }

    private List<DemoData> demoData(int size) {
        List<DemoData> dataList = new ArrayList<>();
        for (int i = 0; i < size; i++) {
            DemoData demoData = new DemoData();
            demoData.setString("String" + i);
            demoData.setDate(DateUtil.date());
            demoData.setDoubleData(RandomUtil.randomDouble());
            dataList.add(demoData);
        }
        return dataList;
    }
}

```

### What did you expect to see?

Read successfully,no exception

#### Exception
`org.apache.poi.openxml4j.exceptions.OLE2NotOfficeXmlFileException: The supplied data appears to be in the OLE2 Format. You are calling the part of POI that deals with OOXML (Office Open XML) Documents. You need to call a different part of POI to process this data (eg HSSF instead of XSSF)`

Image

#### Methion Issue

[easyexcel-issue-3463](https://github.com/alibaba/easyexcel/issues/3463)

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by delei**
Close #393

## What's changed?
- enhance type recognition by considering password-protected files
- refactor encryption test cases

## Checklist

- [x] I have written the necessary doc or comment.
- [x] I have added the necessary unit tests and all cases have passed.

### CODE REVIEW

File: fastexcel-test/src/test/java/cn/idev/excel/test/core/encrypt/EncryptDataTest.java [hunk 1]
```diff
@@ -48,46 +39,61 @@ public static void init() {
...
-        EasyExcel.write(file, EncryptData.class).password("123456").sheet().doWrite(data());
-        EasyExcel.read(file, EncryptData.class, new EncryptDataListener()).password("123456").sheet().doRead();
-    }
-
-    private void readAndWriteStream(File file, ExcelTypeEnum excelType) throws Exception {
-        FileOutputStream fileOutputStream = new FileOutputStream(file);
-        EasyExcel.write(fileOutputStream, EncryptData.class).password("123456").excelType(excelType).sheet()
-            .doWrite(data());
-        fileOutputStream.close();
+    private void readAndWrite(File file, ExcelTypeEnum excelType, boolean hasPassword, boolean isStream)
```
Comment (delei) [inline fastexcel-test/src/test/java/cn/idev/excel/test/core/encrypt/EncryptDataTest.java:84]: the unit test case for csv files is missing.

File: fastexcel-test/src/test/java/cn/idev/excel/test/core/encrypt/EncryptDataTest.java [hunk 2]
```diff
@@ -1,93 +1,116 @@
...
+        Assertions.assertEquals(10, dataList.size());
+        Assertions.assertNotNull(dataList.get(0).getName());
     }
 
     private List<SimpleData> data() {
         List<SimpleData> list = new ArrayList<SimpleData>();
         for (int i = 0; i < 10; i++) {
             SimpleData simpleData = new SimpleData();
-            simpleData.setName("姓名" + i);
+            simpleData.setName("Name" + i);
```
Comment (alaahong) [inline fastexcel-test/src/test/java/cn/idev/excel/test/core/encrypt/EncryptDataTest.java:113]: any issue on unicode value？

File: fastexcel-test/src/test/java/cn/idev/excel/test/core/encrypt/EncryptDataTest.java [hunk 3]
```diff
@@ -1,93 +1,116 @@
...
+    public void t03ReadAndWriteCSV() throws Exception {
+        readAndWrite(fileCsv, null, false, false);
+        readAndWrite(fileCsv, null, true, false);
+        readAndWrite(fileCsv, ExcelTypeEnum.CSV, false, false);
+        readAndWrite(fileCsv, ExcelTypeEnum.CSV, true, false);
+
+        readAndWrite(fileCsvOutputStream, null, false, true);
+        readAndWrite(fileCsvOutputStream, null, true, true);
+        readAndWrite(fileCsvOutputStream, ExcelTypeEnum.CSV, false, true);
+        readAndWrite(fileCsvOutputStream, ExcelTypeEnum.CSV, true, true);
```
Comment (alaahong) [inline fastexcel-test/src/test/java/cn/idev/excel/test/core/encrypt/EncryptDataTest.java:81]: why haspassword with CSV file？

File: fastexcel-core/src/main/java/cn/idev/excel/support/ExcelTypeEnum.java [hunk 4]
```diff
@@ -74,17 +83,20 @@ public static ExcelTypeEnum valueOf(ReadWorkbook readWorkbook) {
...
+                try (BufferedInputStream bufferedInputStream = new BufferedInputStream(new FileInputStream(file))) {
+                    return recognitionExcelType(bufferedInputStream);
                 }
             }
             if (!inputStream.markSupported()) {
                 inputStream = new BufferedInputStream(inputStream);
                 readWorkbook.setInputStream(inputStream);
             }
-            return recognitionExcelType(inputStream);
+            recognitionType = recognitionExcelType(inputStream);
```
Comment (alaahong) [inline fastexcel-core/src/main/java/cn/idev/excel/support/ExcelTypeEnum.java:94]: should we concern to close the inputstream?

File: fastexcel-test/src/test/java/cn/idev/excel/test/core/encrypt/EncryptDataTest.java (hunk 2 above)
Comment (delei) [reply fastexcel-test/src/test/java/cn/idev/excel/test/core/encrypt/EncryptDataTest.java:113]: since this parameter exists, I think it's still necessary to test whether it has any effect on CSV file

File: fastexcel-test/src/test/java/cn/idev/excel/test/core/encrypt/EncryptDataTest.java (hunk 3 above)
Comment (delei) [reply fastexcel-test/src/test/java/cn/idev/excel/test/core/encrypt/EncryptDataTest.java:81]: since this parameter exists, I think it's still necessary to test whether it has any effect on CSV file

File: fastexcel-test/src/test/java/cn/idev/excel/test/core/encrypt/EncryptDataTest.java (hunk 2 above)
Comment (delei) [reply fastexcel-test/src/test/java/cn/idev/excel/test/core/encrypt/EncryptDataTest.java:113]: when reviewing the PR I submitted, the maintainer thought it would be better to use English.

File: fastexcel-core/src/main/java/cn/idev/excel/support/ExcelTypeEnum.java (hunk 4 above)
Comment (delei) [reply fastexcel-core/src/main/java/cn/idev/excel/support/ExcelTypeEnum.java:94]: when users set up using file streaming，the value of this inputStream is called by the get method of `ReadWorkbook`.I don't think we should close it directly here.

File: fastexcel-test/src/test/java/cn/idev/excel/test/core/encrypt/EncryptDataTest.java [hunk 5]
```diff
@@ -1,93 +1,116 @@
...
-        readAndWrite(file03);
+    public void t02ReadAndWrite03() throws Exception {
+        readAndWrite(file03, null, false, false);
+        readAndWrite(file03, null, true, false);
+        readAndWrite(file03, ExcelTypeEnum.XLS, false, false);
+        readAndWrite(file03, ExcelTypeEnum.XLS, true, false);
+
+        readAndWrite(file03OutputStream, null, false, true);
+        readAndWrite(file03OutputStream, null, true, true);
+        readAndWrite(file03OutputStream, ExcelTypeEnum.XLSX, false, true);
```
[the remark this answers is not in the document]
Comment (delei) [reply fastexcel-test/src/test/java/cn/idev/excel/test/core/encrypt/EncryptDataTest.java:67]: This is a test case to test users who have set the wrong type.

File: fastexcel-test/src/test/java/cn/idev/excel/test/core/encrypt/EncryptDataTest.java [hunk 6]
```diff
@@ -1,93 +1,116 @@
...
+        readAndWrite(file03OutputStream, ExcelTypeEnum.XLSX, true, true);
```
[the remark this answers is not in the document]
Comment (delei) [reply fastexcel-test/src/test/java/cn/idev/excel/test/core/encrypt/EncryptDataTest.java:68]: This is a test case to test users who have set the wrong type.

File: fastexcel-test/src/test/java/cn/idev/excel/test/core/encrypt/EncryptDataTest.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (psxjoy) [reply fastexcel-test/src/test/java/cn/idev/excel/test/core/encrypt/EncryptDataTest.java:67]: > This is a test case to test users who have set the wrong type.

不用在意。这个只是 Copilot的第一步code-review。我会确保在合并之前，任何的代码都会由我再次review :)

[the remark this answers is not in the document]
Comment (delei) [reply fastexcel-test/src/test/java/cn/idev/excel/test/core/encrypt/EncryptDataTest.java:67]: This is indeed a great tool to assist with code review.

**Review by psxjoy — APPROVED** [review]
+LGTM
If no one else has a problem with it, I'll merge it into the main branch this week :)
